name: Build and Publish DevOps Tools

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v2
    - name: Build and test DevOps container
      run: |
        cd devops-jenkins-agent
        GIT_BRANCH=${GITHUB_REF#refs/heads/} make build
    - name: Docker meta
      if: ${{ startsWith(github.ref, 'refs/heads/m') || startsWith(github.ref, 'refs/heads/v') }}
      id: docker_meta
      uses: docker/metadata-action@v5
      with:
        images: diegograssato/devops-tools
    - name: Set up QEMU
      if: ${{ startsWith(github.ref, 'refs/heads/m') || startsWith(github.ref, 'refs/heads/v') }}
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      if: ${{ startsWith(github.ref, 'refs/heads/m') || startsWith(github.ref, 'refs/heads/v') }}
      uses: docker/setup-buildx-action@v3
    - name: install cosign
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: 'v2.4.3' 
    - name: Login to DockerHub
      if: ${{ startsWith(github.ref, 'refs/heads/m') || startsWith(github.ref, 'refs/heads/v') }}
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and publish multi-arch kubectl container
      if: ${{ startsWith(github.ref, 'refs/heads/m') || startsWith(github.ref, 'refs/heads/v') }}
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        context: ./devops-jenkins-agent
        push: true
        tags: |
          ${{ github.ref != 'refs/heads/main' && steps.docker_meta.outputs.tags || '' }}
          ${{ github.ref == 'refs/heads/main' && 'diegograssato/devops-tools:latest' || '' }}
        labels: ${{ steps.docker_meta.outputs.labels }} 
    - name: Sign image only on version branches
      if: ${{ startsWith(github.ref, 'refs/heads/v') }}
      run: cosign sign --oidc-issuer https://token.actions.githubusercontent.com ${TAGS}
      env:
        TAGS: ${{ steps.docker_meta.outputs.tags }}
        COSIGN_EXPERIMENTAL: 1
